Repository ScientiaLiber/MindIndex, pull requests merged in 2023-07, with the labels that each got.

#44 SCIEN 55 edit collection view
  components/Basepath.jsx
  components/NavBar.jsx
  components/auth/LoginForm.jsx
  components/auth/RegisterForm.jsx
  components/collection/FlashcardForm.jsx
  components/profile/ProfileForm.jsx
  components/profile/Socials.jsx
  components/profile/UserCollections.jsx
  components/profile/UserNotes.jsx
  components/profile/UserProfile.jsx
  components/search/ListView.jsx
  components/search/SearchBar.jsx
  controllers/Collection.mjs
  next.config.js
  pages/profile.jsx
  pages/study-set/[slug].jsx
  pages/study-set/add.jsx
  pages/test.jsx
Labels: enhancement

#48 feat: add flashcard seed & duplicated row fix
  seeds/002_flashcard_collections.js
  seeds/004_flashcards.js
Labels: enhancement

#50 SCIEN 65 premium user extra features
  components/ClientApi.jsx
  components/NavBar.jsx
  components/auth/LoginForm.jsx
  config/swagger.mjs
  controllers/Auth.mjs
  controllers/Collection.mjs
  controllers/Flashcard.mjs
  controllers/Note.mjs
  controllers/Payment.mjs
  controllers/Profile.mjs
  controllers/Search.mjs
  controllers/User.mjs
  middlewares/Passport.mjs
  middlewares/Restrict.mjs
  models/Collection.mjs
  models/User.mjs
  models/index.mjs
  pages/index.jsx
  pages/study-set/[slug].jsx
  pages/study-set/add.jsx
  routes/api.mjs
  seeds/002_flashcard_collections.js
  seeds/003_notes.js
Labels: bug, documentation, enhancement

#52 SCIEN 50 flashcard view study set
  components/NavBar.jsx
  components/collection/FlashcardItem.jsx
  components/collection/FlashcardListing.jsx
  components/collection/FlashcardViewer.jsx
  components/collection/NoteListing.jsx
  components/collection/ViewerNavButtons.jsx
  components/profile/UserCollections.jsx
  components/profile/UserProfile.jsx
  components/styles/Studyset.module.css
  controllers/Collection.mjs
  migrations/20230703020303_alter_collections_table_add_slug.js
  migrations/20230703022422_alter_notes_table_add_collection_id_fk.js
  models/Collection.mjs
  models/Flashcard.mjs
  models/Note.mjs
  models/Payment.mjs
  models/Profile.mjs
  package-lock.json
  package.json
  pages/study-set/[slug].jsx
  pages/user/study-set/[id].jsx
  pages/user/study-set/add.jsx
  routes/api.mjs
  seeds/002_flashcard_collections.js
Labels: bug, enhancement

#49 Scien 36 create update view note modal
  .gitignore
  components/CreateEditMode.jsx
  components/NavBar.jsx
  components/NoteForm.jsx
  components/ViewMode.jsx
  components/profile/UserNotes.jsx
  components/search/Card.jsx
  components/search/SearchBar.jsx
  components/styles/NoteForm.module.css
  controllers/Note.mjs
  models/Note.mjs
  package-lock.json
  package.json
  pages/search.jsx
Labels: bug, enhancement
